apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour-auto-include-deployment
spec:
  selector:
    matchLabels:
      app: contour-auto-include
  replicas: 1
  template:
    metadata:
      labels:
        app: contour-auto-include
    spec:
      containers:
      - name: contour-auto-include
        image: registry.nordix.org/cloud-native/contour-auto-include:latest
        env:
          - name: __prefix
            value: "example.com/"
          - name: __interval
            value: "10"
