apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour-auto-inlcude-deployment
spec:
  selector:
    matchLabels:
      app: contour-auto-inlcude
  replicas: 1
  template:
    metadata:
      labels:
        app: contour-auto-inlcude
    spec:
      containers:
      - name: contour-auto-inlcude
        image: registry.nordix.org/cloud-native/contour-auto-inlcude:latest

